server:
  port: 8761
spring:
  application: # Application-Info for the Info-Actuator
    name: "@pom.artifactId@"
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
management: # Actuator Configuration
  server:
    port: 8085
  endpoints:
    web:
      exposure:
        include: "*"
