spring:
  boot:
    admin:
      ui:
        theme:
          color: "#f48b33"
          palette:
            50: "#fef1e6"
            100: "#fff2e6"
            200: "#f8b780"
            300: "#f7a866"
            400: "#f59a4d"
            500: "#f48b33"
            600: "#f27d1a"
            700: "#f16e00"
            800: "#d96300"
            900: "#000000"

        title: Orange Apps Admin
        brand: "<img src=\"assets/img/logo.png\"><span>Orange Apps Admin</span>"
        available-languages:
          - en
          - fr
        favicon: logo.png
        login-icon: assets/img/logo.png
        
