spring:
  security:
    user:
      name: "BSCSWS1"
      password: "BSCSWS1"
  boot:
    admin:
      client:
        username: "BSCSWS1"       #These two are needed so that the client
        password: "BSCSWS1"   #can register at the protected server api
        instance:
          metadata:
            user.name: "BSCSWS1"         #These two are needed so that the server
            user.password: "BSCSWS1" #can access the protected client endpoints

info.tags.security: secured
