spring:
  datasource:
    bscs:
      username: SYSADM
      password: SYSADM
      url: jdbc:oracle:thin:@//192.168.10.90:1521/BSCSBCC
      driver-class-name: oracle.jdbc.OracleDriver

    postgres:
      username: postgres
      password: postgres
      url: jdbc:postgresql://192.168.10.70:5431/OTNWS
      driver-class-name: org.postgresql.Driver
