endpoint:
  service:
    wsi:
      url: http://192.168.10.95:13001/wsi/services/
      username: BSCSWS1
      password: BSCSWS1

    ### CustomerHandling Web Service Endpoint ######
    customer-handling:
      url: http://192.168.10.54:8080/CustomerHandling/services/CustomerHandling?wsdl
      user: BSCSWS1
      pass: BSCSWS1
