endpoint:
  service:
    wsi:
      url: http://192.168.10.95:13001/wsi/services/
      username: ADMXZ
      password: ADMX

    ### CustomerHandling Web Service Endpoint ######
    customer-handling:
      url: http://192.168.10.54:8080/CustomerHandling/services/CustomerHandling?wsdl
      user: ADMX
      pass: ADMX
